kylin:
  server:
    port: 8888
  cloud:
    app:
      version: 0.9.0
      description: 配置中心
    contextPath: /configserver
#logging:
#  level:
#    org:
#      springframework:
#        security: INFO
#security:
#  ignored:
#    - log4j2*
